### ISSUE TITLE
pip package is not (yet?) available

### ISSUE THREAD

**Issue by wouterpotters** [reiniervlinschoten/castoredc_api#1]
`pip install castoredc-api-client`
_ERROR: Could not find a version that satisfies the requirement castoredc-api-client (from versions: none)
ERROR: No matching distribution found for castoredc-api-client_

`pip install castoredc-api-client==1.0.5 `
_ERROR: Could not find a version that satisfies the requirement castoredc-api-client==1.0.5 (from versions: none)
ERROR: No matching distribution found for castoredc-api-client==1.0.5_

**Comment by reiniervlinschoten** [comment]
First dev version published: https://pypi.org/project/castoredc-api/
