### ISSUE TITLE
package vs. individual repositories

### ISSUE THREAD

**Issue by wouterpotters** [reiniervlinschoten/castoredc_api#14]
To me, it is currently unclear how the combined package and individual import, study, client packages are organized.

I think it would make sense to have:
- 1 package in 1 github repository with all code and 1 pip repo. 
- if you really want all the client, study and import classes in a seperate github repository, you could use submodules (https://git-scm.com/book/en/v2/Git-Tools-Submodules) to avoid duplicate code.

_(just a suggestion, so feel free to close this issue without any follow-up)_

**Comment by reiniervlinschoten** [comment]
Individual packages are going to be deprecated and point to the combined package, only the combined package will appear on pip and conda.
