### ISSUE TITLE
Conda: Make conda package available

### ISSUE THREAD

**Issue by wouterpotters** [reiniervlinschoten/castoredc_api#2]
Some people like to use anaconda and/or conda. It is relatively easy to create a conda package from an existing PIP package: E.g. using shell script https://github.com/wouterpotters/castorapi/blob/master/conda.sh

**Comment by reiniervlinschoten** [comment]
Conda package is available through channel reiniervl (see readme). Working on conda-forge.

**Comment by reiniervlinschoten** [comment]
Conda-forge pull request made
https://github.com/conda-forge/staged-recipes/pull/16250
