### ISSUE TITLE
circular import

### ISSUE THREAD

**Issue by seaaxe** [reiniervlinschoten/castoredc_api#27]
getting:
ImportError: cannot import name '_pickle' from partially initialized module 'numpy.random' (most likely due to a circular import) (...venv\lib\site-packages\numpy\random\__init__.py)

**Comment by reiniervlinschoten** [comment]
Please add information about what you are trying to do and how to reproduce the error.

**Comment by reiniervlinschoten** [comment]
No extra information given, and can't reproduce error. Closed.
