### ISSUE TITLE
Rely on response's `Content-Type` to determine if it is JSON or CSV

### ISSUE THREAD

**Issue by andreasCastor** [reiniervlinschoten/castoredc_api#3]
In several places, we pass `content_type` to functions, e.g.

```python
data = self.castor_get(url=url, params=None, content_type="JSON")
```

However, just by inspecting the response's `Content-Type` header, we can figure out if it is JSON or something else.

**Comment by reiniervlinschoten** [comment]
Fixed in forthcoming update.
