### ISSUE TITLE
Run unit tests, sanity checks, style check in github actions

### ISSUE THREAD

**Issue by andreasCastor** [reiniervlinschoten/castoredc_api#6]
Github actions is a free CI system which makes it easy to run style checkers (e.g. `black`), linters (e.g. `pylint`, `mypy`), and unit tests.

**Comment by reiniervlinschoten** [comment]
Added pylint, but not accepting fail-under parameter?

**Comment by reiniervlinschoten** [comment]
Added pylint, pytest (integration for master and unittest for all but master) and black check in workflows.
