### ISSUE TITLE
Tests: Write documentation on how to run tests

### ISSUE THREAD

**Issue by andreasCastor** [reiniervlinschoten/castoredc_api#7]
I see there's a decent test suite, but I could not figure out what I needed to run them.

The tests seem to mostly be integration tests which hit data.castoredc.com, and I see a few hard-coded UUIDs which I assume will only work if the account being used to test with is yours.

If there are unit tests that don't need to connect to EDC, those could be split into a separate directory so that it's easy to run just those tests. Those could also be ran in CI.

**Comment by reiniervlinschoten** [comment]
TODO:

- [ ] Write Readme on running tests
- [ ] Create scripts for autofilling new studies in Castor with the necessary test information
- [ ] Fix #17
