### ISSUE TITLE
Client: Rate Limiting

### ISSUE THREAD

**Issue by reiniervlinschoten** [reiniervlinschoten/castoredc_api#71]
Castor News
API coming updates
We are also planning to gradually introduce rate limiting for selected API endpoints, in order to ensure proper performance of our service.

IMPORTANT NOTE: Please review your API integrations to make sure they can handle rate limiting responses, specified as having a 429 HTTP response code.

We should add better handling of the rate limiting responses, for example with: https://github.com/florimondmanca/aiometer
And possible add handling 429 responses explicitly by for example retrying.

**Comment by priya-gitTest** [comment]
How to get the output of this function to a pandas dataframe : 
# Get all records
c.all_records()
 I tried various options including this one below but get errors
df = pd.DataFrame.from_records(c)
TypeError: object of type 'CastorClient' has no len()

or 
df = pd.DataFrame(c)
DataFrame constructor not properly called!

**Comment by priya-gitTest** [comment]
> How to get the output of this function to a pandas dataframe :
> 
> # Get all records
> c.all_records() I tried various options including this one below but get errors df = pd.DataFrame.from_records(c) TypeError: object of type 'CastorClient' has no len()
> 
> or df = pd.DataFrame(c) DataFrame constructor not properly called!

Also, the output is not a proper python list . 
print(type(c))
<class 'castoredc_api.client.castoredc_api_client.CastorClient'>

**Comment by priya-gitTest** [comment]
similar issue and the solution mentioned there also doesnt work :(

https://stackoverflow.com/questions/63100487/how-to-parse-a-list-and-a-dictionary-openapi-and-swagger-in-python/63100789#63100789

**Comment by reiniervlinschoten** [comment]
@priya-gitTest, see #78, as this is not the right issue for your question.

**Comment by reiniervlinschoten** [comment]
Currently works through limit in HTTPx client, but should probably switch to a more robust method using aiometer and reading rate limiting headers.

**Comment by reiniervlinschoten** [comment]
Fixed in #87
