### ISSUE TITLE
How to get the output of this function to a pandas dataframe :

### ISSUE THREAD

**Issue by reiniervlinschoten** [reiniervlinschoten/castoredc_api#78]
How to get the output of this function to a pandas dataframe : 
# Get all records
c.all_records()
 I tried various options including this one below but get errors
df = pd.DataFrame.from_records(c)
TypeError: object of type 'CastorClient' has no len()

or 
df = pd.DataFrame(c)
DataFrame constructor not properly called!

_Originally posted by @priya-gitTest in https://github.com/reiniervlinschoten/castoredc_api/issues/71#issuecomment-1202794587_

**Comment by reiniervlinschoten** [comment]
@priya-gitTest

If you just want to get all your records, do the following after you have instantiated your client.
```python
records = c.all_records()
```
This returns a list of dicts of all records.

If you want all you data from the study in a pandas dataframe, do:
```python
study = CastorStudy(
    "YOURCLIENTID",
    "YOURCLIENTSECRET",
    "YOURSTUDYID",
    "data.castoredc.com",
)
data = study.export_to_dataframe()
```

**Comment by priya-gitTest** [comment]
Hi, Thanks for replying.
I had deleted my comments as I had figured out how to make it work for my requirements.
Its 
b=list(c.all_records(archived=0))
df_castorStudy = pd.DataFrame.from_records(b)
print(df_castorStudy.shape)
