### ISSUE TITLE
Importing data leads to error

### ISSUE THREAD

**Issue by okroonaumc** [reiniervlinschoten/castoredc_api#85]
Following the readme gives me the following error. Is this error caused by my castor structure?

<img width="1014" alt="Screenshot 2023-02-21 at 16 18 54" src="https://user-images.githubusercontent.com/108735535/220385130-491bcde5-a37b-4d19-a46e-bf694b3f466c.png">
<img width="1009" alt="Screenshot 2023-02-21 at 16 22 57" src="https://user-images.githubusercontent.com/108735535/220386147-3eff7533-a9df-4306-b4ed-29ac719a6df7.png">

**Comment by reiniervlinschoten** [comment]
It is hard to diagnose when not knowing what your study looks like, but it seems like in the row above:

```python
    target_field = study.get_single_field(new_name[0]) # <-- Here
    # Check if we want to validate field exists for parent
    # This can be None for testing purposes
    if target == "Study":
        # Check for study
        if target_field.step.form.form_type != "Study":
```

Target field is not found, and then this function returns none.
Can you show me the column link file, and verify for me that every column name exists as a field in you study?

**Comment by okroonaumc** [comment]
Thanks for the reply! In this case I tried to only upload the record ids.  It turned out the issue was using 'recordId' instead of 'record_id'. Currently however, I get the error in the output csv that the record does not exist in the study. Should I First upload them via the api in the image below (using free text participant id's)?

<img width="301" alt="Screenshot 2023-02-22 at 16 50 36" src="https://user-images.githubusercontent.com/108735535/220678331-62a98878-adf7-4652-b9f8-f4739a2f40d7.png">
<img width="1417" alt="Screenshot 2023-02-22 at 17 03 30" src="https://user-images.githubusercontent.com/108735535/220683165-d0c3daf1-e775-4422-91f3-6616df809860.png">

**Comment by reiniervlinschoten** [comment]
Yes, records first have to exist in the study. You can use the client to create the records.
If you have linked the study in the API you can use:

```python
study.client.create_record(institute_id, email, record_id)
        """Creates a record. Record_id is only necessary when id generation
        strategy is set to free text. Ccr_patient_id is an optional parameter.
        Returns None when record creation failed."""
```
You can put in None for email if you don't want to add an email.
Record_id is only necessary if you have free text record_ids

**Comment by reiniervlinschoten** [comment]
Closing this now, let me know if you have any other question.
