### ISSUE TITLE
Client: Data export not respecting archived parameter

### ISSUE THREAD

**Issue by reiniervlinschoten** [reiniervlinschoten/castoredc_api#89]
It seems the client.export_study_data endpoint does not adequately respect the archived parameter, returning archived reports when it is set to False. For now this means we can't filter on archived at the API, leading to a problem when exporting study data.
Currently we extract all data and then filter it ourselves.

Call has been opened.

```python
    # DATA ANALYSIS
    def export_to_dataframe(self, archived=False) -> dict:
        """Exports all data from a study into a dict of dataframes for statistical analysis."""
        # TODO: change this to the correct archived,
        #  fails now because the parameter does not seem to be handled correctly server side
        self.map_data(archived=True)
        dataframes = {
            "Study": self.__export_study_data(archived),
            "Surveys": self.__export_survey_data(archived),
            "Reports": self.__export_report_data(archived),
        }
        return dataframes
```

**Comment by slknijnenburg** [comment]
This issue will be fixed with the next CDMS maintenance release (2023.2.2.0), which is planned for end of June.
